name: "Run mabl tests"
description: "Register a deployment event with mabl and run associated tests"
branding:
  icon: play-circle
  color: white
inputs:
  application-id:
    description: ^
      'the mabl id for the deployed application.  You can get the id using the
      curl builder at https://app.mabl.com/workspaces/-/settings/apis. Either
      this or environment-id must be provided'
    required: false
  environment-id:
    description: ^
      'the mabl id for the deployed environment. You can get the id using the
      curl builder at https://app.mabl.com/workspaces/-/settings/apis.  Either
      this or application-id must be provided'
    required: false
  browser-types:
    description: ^
      'override for the browser types to test.  If not provided, mabl will test
      the browsers configured on the triggered test plans.'
    required: false
  uri:
    description: ^
      'the base uri to test against.  If provided, this will override the default uri
      associated with the environment in mabl'
    required: false
  rebaseline-images:
    description: ^
      'Set to true to reset the visual baseline to the current deployment'
    required: false
    default: false
  set-static-baseline:
    description: ^
      'Set to true to use the current deployment as an exact static
      baseline.  If this is set, mabl will not model dynamic areas and will use
      the current deployment as a pixel-exact visual baseline.'
    required: false
    default: false
  continue-on-failure:
    description: ^
      'Set to true to continue the build even if there are test failures'
    required: false
    default: false
  event-time:
    description: "The event time the deployment happened at.  Defaults to now."
    required: false
outputs:
  mabl-deployment-id:
    description: "mabl deployment event id"
  plans_run:
    description: "total number of mabl plans run against this deployment.  A mabl plan is a collection of similarly configured tests."
  plans_passed:
    description: "number of mabl plans that passed against this deployment.  A mabl plan is a collection of similarly configured tests."
  plans_failed:
    description: "number of mabl plans that failed against this deployment.  A mabl plan is a collection of similarly configured tests."
  journeys_run:
    description: "total number of mabl journeys run against this deployment.  A mabl journey is an end to end test of your application."
  journeys_passed:
    description: "number of mabl journeys that passed against this deployment.  A mabl journey is an end to end test of your application."
  journeys_failed:
    description: "number of mabl journeys that failed against this deployment.  A mabl journey is an end to end test of your application."

runs:
  using: "node12"
  main: "lib/index.js"
