on: [push]

name: mabl

jobs:
  test:
    name: Mabl Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Functional test deployment
        id: mabl-test-deployment
        uses: ./deploy-and-test/
        env:
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
        with:
          application-id: l-j3VqIO6lLLOOEoFTPSxA-a
          environment-id: rtb4kWD5LuTr2KxaHvwfaA-e
