on: [push]

name: mabl

jobs:
  test:
    name: Mabl Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run check

      - name: Run Tests
        run: npm test

      - name: Compile Typescript
        run: npm run build

      - name: Run mabl tests against deployment
        id: mabl-test-deployment
        uses: ./
        env:
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          application-id: D6uz-lhAGBYuTTc6Jj_w0Q-a
          environment-id: I9tfo2dWd7WSigXcO91feA-e
          browser-types: chrome
